-- liquibase formatted sql
-- changeset Mihail:1
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    password   VARCHAR(255),
    phone      VARCHAR(255),
    role       VARCHAR(255),
    image_id   INTEGER
);

-- changeset Anna:2
CREATE TABLE ads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    price       INTEGER,
    title       VARCHAR(255),
    author_id   BIGINT REFERENCES users (id),
    image_id    INTEGER
);

-- changeset Vadim:3
CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    text       VARCHAR(255),
    ad_id      BIGINT REFERENCES ads (id),
    author_id  BIGINT REFERENCES users (id)
);

-- changeset Anna:4
CREATE TABLE image
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data BYTEA,
    media_type VARCHAR(255)
);
